# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/classroom-monitor',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/classroom-monitor',
                'lib_path': 'classroom_monitor'},
  'syms': { 'classroom_monitor.core': {'classroom_monitor.core.foo': ('template.html#foo', 'classroom_monitor/core.py')},
            'classroom_monitor.database': { 'classroom_monitor.database.Frame': ('database.html#frame', 'classroom_monitor/database.py'),
                                            'classroom_monitor.database.Queryable.schema': ( 'database.html#queryable.schema',
                                                                                             'classroom_monitor/database.py'),
                                            'classroom_monitor.database.Run': ('database.html#run', 'classroom_monitor/database.py'),
                                            'classroom_monitor.database.RunFrame': ( 'database.html#runframe',
                                                                                     'classroom_monitor/database.py'),
                                            'classroom_monitor.database.Video': ('database.html#video', 'classroom_monitor/database.py'),
                                            'classroom_monitor.database.reset_tables': ( 'database.html#reset_tables',
                                                                                         'classroom_monitor/database.py')}}}
