# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/classroom-monitor',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/classroom-monitor',
                'lib_path': 'classroom_monitor'},
  'syms': {'classroom_monitor.core': {'classroom_monitor.core.foo': ('core.html#foo', 'classroom_monitor/core.py')}}}
