"""Fill in a module description here

Docs: https://ForBo7.github.io/classroom-monitortemplate.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/TEMPLATE.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/TEMPLATE.ipynb #da4d26dd
def foo(): pass
